[build]
  bin = "main"          
  cmd = "go run modules/server/server-starter.module.go"
  include = ["*.go", "modules/**/*.go", "servers/**/*.go"]
  exclude = ["tmp"]

[log]
  time = "true"

[watch]
  delay = 1000
  watch = ["*.go", "modules/**/*.go", "servers/**/*.go", "configs/*.yml"]
